---
- name: copy job exec file
  template:
    src: "Register-CronTasks.ps1.j2"
    dest: "/usr/local/bin/Register-CronTasks.ps1"
    mode: 0740

- name: Creates a cron file under /etc/cron.d
  cron:
    name: "zabbix_discovery_tasks"
    weekday: "*"
    minute: "40"
    hour: "3"
    user: "root "
    job: "/usr/local/bin/Register-CronTasks.ps1"
    cron_file: "ansible_zabbix_discovery_tasks"



