---
- name: copy job exec file
  template:
    src: "{{ item.template }}"
    dest: "{{ item.job }}"
    mode: 0740
  when: item.template is defined
  with_items:
    - "{{ cron_discovery_tasks }}"

- name: Creates a cron file under /etc/cron.d
  cron:
    name: "{{ item.name }}"
    weekday: "{{ item.weekday }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    user: "{{ item.user | default ('root') }}"
    job: "{{ item.job }}"
    cron_file: "ansible_{{ item.name }}"
  with_items:
    - "{{ cron_discovery_tasks }}"
  when: cron_discovery_tasks is defined



