---
- name: Ensure zabbix sender installed
  apt:
    update_cache: yes
    name: zabbix-sender

- name: Ensure cron log dir exists
  file:
    path: "{{ cron_zabbix_log_path }}"
    state: directory

- name: copy job exec file
  template:
    src: "Register-CronTasks.ps1.j2"
    dest: "/usr/local/bin/Register-CronTasks.ps1"
    mode: 0740

- name: Creates a cron file under /etc/cron.d
  cron:
    name: "zabbix_discovery_tasks"
    minute: "{{ cron_discovery_task.minute | default ('*')}}"
    hour: "{{ cron_discovery_task.hour | default ('*') }}"
    day: "{{ cron_discovery_task.day | default ('*') }}"
    month: "{{ cron_discovery_task.month | default ('*') }}"
    weekday: "{{ cron_discovery_task.weekday | default ('*') }}"
    user: "root "
    job: "/usr/local/bin/Register-CronTasks.ps1"
    cron_file: "ansible_zabbix_discovery_tasks ; zabbix_sender -z zabbix.agrohistory.local -s mongodbmn-02.agrohistory.local -k trap[ansible_zabbix_discovery_tasks] -o $? >> /var/log/cron/ansible_zabbix_discovery_tasks"



